In [10]:
from sklearn import preprocessing
import numpy as np
from sklearn.preprocessing import Imputer
import pandas as pd

In [11]:
# bining example

In [17]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]

binarizer = preprocessing.Binarizer(threshold=1.5)
print(binarizer,"\n")

binned_x = binarizer.transform(X)
print(binned_x, "\n")

Binarizer(copy=True, threshold=1.5) 

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]] 



In [19]:
print("missing values example: \n")
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit([[1, 2], [np.nan, 3], [7, 6]])
X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X), "\n")

missing values example: 

[[ 2.  2.]
 [ 6.  6.]
 [ 7.  6.]] 



In [14]:
# min max standarize
print("example 1 data: \n")
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
print(X_train, "\n")

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)

print("standarize with min-max: \n", X_train_minmax, "\n")

example 1 data: 

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]] 

standarize with min-max: 
 [[ 0.5         0.          1.        ]
 [ 1.          0.5         0.33333333]
 [ 0.          1.          0.        ]] 



In [15]:
# z-score standarize
print("example 2 data: \n")
X_train = np.array([[ 1., -1.,  2.],
                   [ 2.,  0.,  0.],
                   [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train)

print("standarize with z-score: \n", X_scaled, "\n")
print("mean :", X_scaled.mean(axis=0))
print("std: ", X_scaled.std(axis=0))

example 2 data: 

standarize with z-score: 
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]] 

mean : [ 0.  0.  0.]
std:  [ 1.  1.  1.]


In [20]:
# discretize 

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])

bins = [0, 25, 50, 75, 100]
group_names = ['Low', 'Okay', 'Good', 'Great']

categories = pd.cut(df['postTestScore'], bins, labels=group_names)

df['categories'] = categories
df['scoresBinned'] = pd.cut(df['postTestScore'], bins)

print(df)

      regiment company      name  preTestScore  postTestScore categories  \
0   Nighthawks     1st    Miller             4             25        Low   
1   Nighthawks     1st  Jacobson            24             94      Great   
2   Nighthawks     2nd       Ali            31             57       Good   
3   Nighthawks     2nd    Milner             2             62       Good   
4     Dragoons     1st     Cooze             3             70       Good   
5     Dragoons     1st     Jacon             4             25        Low   
6     Dragoons     2nd    Ryaner            24             94      Great   
7     Dragoons     2nd      Sone            31             57       Good   
8       Scouts     1st     Sloan             2             62       Good   
9       Scouts     1st     Piger             3             70       Good   
10      Scouts     2nd     Riani             2             62       Good   
11      Scouts     2nd       Ali             3             70       Good   

   scoresBi